### ISSUE TITLE
Null reference exception when a region is added in a component presentation on the page and in an include of that same page

### ISSUE THREAD

**Issue by HaraldHoffelinck** [sdl/dxa-web-application-java#62] opened 2016-09-20 09:15 UTC
If a page contains a component presentation with a certain region name, and an include of that page contains the same region name, then we get a null reference exception in the page builder.

**Comment by rpannekoek** [comment] 2016-10-04 15:38
TSI-2006 (internal issue ID for tracking purposes)

**Comment by azarakovsky** [comment] 2016-12-14 15:02
@HaraldHoffelinck we were not able to reproduce the issue on 1.5 but your code change seems OK, so I merged it in 1.7. Hope it solves the issue.

I would appreciate if you can provide details how to reproduce it.

**Comment by rpannekoek** [comment] 2016-12-22 20:05
Fixed in DXA 1.7

**Closed by rpannekoek** 2016-12-22 20:05 UTC
Labels: bug
