### ISSUE TITLE
Http probe requests fails in absence of Accept or Content-Type parameter in header

### ISSUE THREAD

**Issue by puneetkk** [sdl/dxa-web-application-java#8] opened 2016-01-05 09:02 UTC
Linked from my post in Stackexchange :-  [link to Post](http://tridion.stackexchange.com/questions/13597/dxa-1-2-http-probe-requests-fails-in-absence-of-accept-or-content-type-paramet)

After recently upgrading to DXA 1.2, have noticed that new PageController introduced handleGetPageFormatted() which is suppose to be used for responding with formatted (mostly other than text/html) output for a requested resource.

This works fine almost most of the time except in case, there is no Accept header parameter in request. DefaultDataFormatter's getHtmlAcceptScore() gives null pointer exception, in absence of Accept header parameter.

In our we are using Varnish Cache, which is configured as part of our load balancer setup. This varnish cache probes the application boxes for availability. If the servers fails to respond the probe they are marked sick and not reachable. After investigation understood that by default it doesn't send any header. Settings below for a probe:

backend www1 { .host = "xx.xx.xx.xx"; .port = "80"; .probe = { .url = "/"; .interval = 5s; .timeout = 3s; .window = 5; .threshold = 3; } }

By having a consumes attribute set on handleGetPageFormatted()'s @RequestMapping , could solve problem. As it would mean only map the request which accepts a particular type of Media Type.

Edit: Another way to address could be by sending the Accept header as part of Probe request itself, which was not the requirement in earlier version of DXA. Example below:

.request =
    "GET /probe.cgi HTTP/1.1"
    "Host: 127.0.0.2"
    "Connection: close"
    "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8"
    "Accept-Encoding: foo/bar" ;

**Comment by jhorsman** [comment] 2016-01-05 10:00
Thanks for reporting this interesting issue!

Adding the `Accept` header to the probe request is a nice workaround. I think the webapp should be able to handle requests without the Accept header. The values in the Accept hearder are probably ignored anyway since this is not really a nice header (http://www.newmediacampaigns.com/blog/browser-rest-http-accept-headers).

**Comment by puneetkk** [comment] 2016-01-05 10:04
A null check for request.getHeader("Accept") in getHtmlAcceptScore(), would help us save changes any where.

**Comment by jhorsman** [comment] 2016-01-19 09:08
I could reproduce this issue with telnet.

`telnet localhost 9080`

once in the session send the request
```
GET /index.html HTTP/1.1
host: localhost
<line feed>
```

**Comment by azarakovsky** [comment] 2016-01-22 14:16
https://github.com/sdl/dxa-web-application-java/pull/19 is merged

**Closed by azarakovsky** 2016-01-22 14:16 UTC
Labels: bug
